CREATE TABLE T_OLIMPIADAS (
    CODIGO VARCHAR(30) PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100),
    YEAR INT NOT NULL
);

CREATE TABLE T_ITINERARIOS (
    CODIGO VARCHAR(30) PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100),
    OLIMPIADA VARCHAR(30) NOT NULL,
    FOREIGN KEY (OLIMPIADA)
        REFERENCES T_OLIMPIADAS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_RUBRICAS (
    CODIGO VARCHAR(30) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION VARCHAR(100),
    PUNTOS_RUBRICA VARCHAR(50) NOT NULL,
    ETIQUETAS_RUBRICA VARCHAR(300)
);

CREATE TABLE T_EJERCICIOS (
    CODIGO VARCHAR(30) PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200),
    CONCEPTO VARCHAR(40) NOT NULL CHECK (CONCEPTO IN (
        'ABSTRACCION','ALGORITMOS','BUCLES','CONDICIONALES','DESCOMPOSICION',
        'FUNCIONES','IA','RECONOCIMIENTO DE PATRONES','SECUENCIAS',
        'SECUENCIAS Y BUCLES','VARIABLES','VARIABLES Y FUNCIONES','OTRO'
    )),
    RECURSOS VARCHAR(20) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('ENCHUFADA','DESENCHUFADA')),
    RUBRICA VARCHAR(30) NOT NULL,
    FOREIGN KEY (RUBRICA)
        REFERENCES T_RUBRICAS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_EJERCICIOS_OLIMPIADA_ITINERARIO (
    EJERCICIO VARCHAR(30) NOT NULL,
    OLIMPIADA VARCHAR(30) NOT NULL,
    ITINERARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY (EJERCICIO, OLIMPIADA, ITINERARIO),
    FOREIGN KEY (EJERCICIO)
        REFERENCES T_EJERCICIOS (CODIGO)
        ON UPDATE CASCADE,
    FOREIGN KEY (OLIMPIADA)
        REFERENCES T_OLIMPIADAS (CODIGO)
        ON UPDATE CASCADE,
    FOREIGN KEY (ITINERARIO)
        REFERENCES T_ITINERARIOS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_EQUIPOS (
    CODIGO VARCHAR(30) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    CENTRO_EDUCATIVO VARCHAR(200),
    ITINERARIO VARCHAR(30) NOT NULL,
    P_ABSTRACCION INT,
    P_ALGORITMOS INT,
    P_BUCLES INT,
    P_CONDICIONALES INT,
    P_DESCOMPOSICION INT,
    P_FUNCIONES INT,
    P_IA INT,
    P_REC_PATRONES INT,
    P_SECUENCIAS INT,
    P_SECUENCIAS_Y_BUCLES INT,
    P_VARIABLES INT,
    P_VARIABLES_Y_FUNC INT,
    P_OTROS INT,
    UNIQUE (NOMBRE, ITINERARIO),
    FOREIGN KEY (ITINERARIO)
        REFERENCES T_ITINERARIOS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_USUARIOS (
    NOMBRE VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(50),
    TIPO VARCHAR(20) CHECK (TIPO IN ('ADMINISTRADOR','MONITOR','ORGANIZADOR', 'PARTICIPANTE'))
);

CREATE TABLE T_MONITORES (
    NOMBRE VARCHAR(30) NOT NULL,
    EJERCICIO VARCHAR(30) NOT NULL,
    OLIMPIADA VARCHAR(30) NOT NULL,
    ITINERARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY (NOMBRE, EJERCICIO, OLIMPIADA, ITINERARIO),
    FOREIGN KEY (NOMBRE)
        REFERENCES T_USUARIOS (NOMBRE)
        ON UPDATE CASCADE,
    FOREIGN KEY (EJERCICIO)
        REFERENCES T_EJERCICIOS (CODIGO)
        ON UPDATE CASCADE,
    FOREIGN KEY (OLIMPIADA)
        REFERENCES T_OLIMPIADAS (CODIGO)
        ON UPDATE CASCADE,
    FOREIGN KEY (ITINERARIO)
        REFERENCES T_ITINERARIOS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_ORGANIZADORES (
    ORGANIZADOR VARCHAR(30),
    ITINERARIO VARCHAR(30),
    PRIMARY KEY (ORGANIZADOR, ITINERARIO),
    FOREIGN KEY (ORGANIZADOR)
        REFERENCES T_USUARIOS (NOMBRE)
        ON UPDATE CASCADE,
    FOREIGN KEY (ITINERARIO)
        REFERENCES T_ITINERARIOS (CODIGO)
        ON UPDATE CASCADE
);

CREATE TABLE T_PARTICIPANTES (
    PARTICIPANTE VARCHAR(30),
    ITINERARIO VARCHAR(30),
    P_ALGORITMOS INT,
    P_BUCLES INT,
    P_CONDICIONALES INT,
    P_DESCOMPOSICION INT,
    P_FUNCIONES INT,
    P_IA INT,
    P_REC_PATRONES INT,
    P_SECUENCIAS INT,
    P_SECUENCIAS_Y_BUCLES INT,
    P_VARIABLES INT,
    P_VARIABLES_Y_FUNC INT,
    P_OTROS INT,
    PRIMARY KEY (PARTICIPANTE, ITINERARIO),
    FOREIGN KEY (PARTICIPANTE),
        REFERENCES T_USUARIOS (NOMBRE)
        ON UPDATE CASCADE
    FOREIGN KEY (ITINERARIO),
        REFERENCES T_ITINERARIOS (CODIGO)
        ON UPDATE CASCADE,
        P_ABSTRACCION INT,
    UNIQUE (PARTICIPANTE, ITINERARIO)
);

-- Insertar admin inicial solo si NO existe
INSERT INTO T_USUARIOS (NOMBRE, PASSWORD, TIPO)
SELECT 'ADMIN1', 'ADMIN1', 'ADMINISTRADOR'
WHERE NOT EXISTS (
    SELECT 1 FROM T_USUARIOS WHERE NOMBRE = 'ADMIN1'
);

