CREATE DATABASE IF NOT EXISTS OLYMPULL_DB;

USE OLYMPULL_DB;

CREATE TABLE IF NOT EXISTS T_OLIMPIADAS (
    CODIGO varchar(30) NOT NULL,
    TITULO varchar(50) NOT NULL,
    DESCRIPCION varchar(100) DEFAULT NULL,
    YEAR int NOT NULL,
    PRIMARY KEY (CODIGO),
    UNIQUE KEY TITULO (TITULO)
);

CREATE TABLE IF NOT EXISTS T_ITINERARIOS (
    CODIGO varchar(30) NOT NULL,
    TITULO varchar(50) NOT NULL,
    DESCRIPCION varchar(100) DEFAULT NULL,
    OLIMPIADA varchar(30) NOT NULL,
    PRIMARY KEY (CODIGO),
    KEY OLIMPIADA (OLIMPIADA),
    UNIQUE KEY TITULO (TITULO),
    CONSTRAINT T_ITINERARIOS_ibfk_1 FOREIGN KEY (OLIMPIADA) REFERENCES T_OLIMPIADAS (CODIGO) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS T_RUBRICAS (
    CODIGO varchar(30) NOT NULL,
    NOMBRE varchar(50) DEFAULT NULL,
    DESCRIPCION varchar(100) DEFAULT NULL,
    PUNTOS_RUBRICA varchar(50) NOT NULL,
    ETIQUETAS_RUBRICA varchar(300) DEFAULT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS T_EJERCICIOS (
    CODIGO varchar(30) NOT NULL,
    TITULO varchar(50) NOT NULL,
    DESCRIPCION varchar(200) DEFAULT NULL,
    CONCEPTO enum('ABSTRACCION','ALGORITMOS','BUCLES','CONDICIONALES','DESCOMPOSICION','FUNCIONES','IA','RECONOCIMIENTO DE PATRONES','SECUENCIAS','SECUENCIAS Y BUCLES','VARIABLES','VARIABLES Y FUNCIONES','OTRO') NOT NULL,
    RECURSOS varchar(20) NOT NULL,
    TIPO enum('ENCHUFADA','DESENCHUFADA') NOT NULL,
    RUBRICA varchar(30) NOT NULL,
    PRIMARY KEY (CODIGO),
    KEY RUBRICA (RUBRICA),
    CONSTRAINT T_EJERCICIOS_ibfk_1 FOREIGN KEY (RUBRICA) REFERENCES T_RUBRICAS (CODIGO) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS T_EJERCICIOS_OLIMPIADA_ITINERARIO (
    EJERCICIO varchar(30) NOT NULL,
    OLIMPIADA varchar(30) NOT NULL,
    ITINERARIO varchar(30) NOT NULL,
    PRIMARY KEY (EJERCICIO,OLIMPIADA,ITINERARIO),
    UNIQUE KEY EJERCICIO (EJERCICIO,OLIMPIADA),
    KEY OLIMPIADA (OLIMPIADA),
    KEY ITINERARIO (ITINERARIO),
    CONSTRAINT T_EJERCICIOS_OLIMPIADA_ITINERARIO_ibfk_1 FOREIGN KEY (EJERCICIO) REFERENCES T_EJERCICIOS (CODIGO) ON UPDATE CASCADE,
    CONSTRAINT T_EJERCICIOS_OLIMPIADA_ITINERARIO_ibfk_2 FOREIGN KEY (OLIMPIADA) REFERENCES T_OLIMPIADAS (CODIGO) ON UPDATE CASCADE,
    CONSTRAINT T_EJERCICIOS_OLIMPIADA_ITINERARIO_ibfk_3 FOREIGN KEY (ITINERARIO) REFERENCES T_ITINERARIOS (CODIGO) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS T_EQUIPOS (
    CODIGO varchar(30) NOT NULL,
    NOMBRE varchar(50) DEFAULT NULL,
    CENTRO_EDUCATIVO varchar(200) DEFAULT NULL,
    ITINERARIO varchar(30) NOT NULL,
    P_ABSTRACCION int DEFAULT NULL,
    P_ALGORITMOS int DEFAULT NULL,
    P_BUCLES int DEFAULT NULL,
    P_CONDICIONALES int DEFAULT NULL,
    P_DESCOMPOSICION int DEFAULT NULL,
    P_FUNCIONES int DEFAULT NULL,
    P_IA int DEFAULT NULL,
    P_REC_PATRONES int DEFAULT NULL,
    P_SECUENCIAS int DEFAULT NULL,
    P_SECUENCIAS_Y_BUCLES int DEFAULT NULL,
    P_VARIABLES int DEFAULT NULL,
    P_VARIABLES_Y_FUNC int DEFAULT NULL,
    P_OTROS int DEFAULT NULL,
    PRIMARY KEY (CODIGO),
    UNIQUE KEY NOMBRE (NOMBRE,ITINERARIO),
    KEY ITINERARIO (ITINERARIO),
    CONSTRAINT T_EQUIPOS_ibfk_1 FOREIGN KEY (ITINERARIO) REFERENCES T_ITINERARIOS (CODIGO) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS T_USUARIOS (
    NOMBRE varchar(30) NOT NULL,
    PASSWORD varchar(50) DEFAULT NULL,
    TIPO enum('ADMINISTRADOR','MONITOR','ORGANIZADOR') DEFAULT NULL,
    PRIMARY KEY (NOMBRE)
);

CREATE TABLE IF NOT EXISTS T_MONITORES (
    NOMBRE varchar(20) NOT NULL,
    EJERCICIO varchar(50) NOT NULL,
    OLIMPIADA varchar(50) NOT NULL,
    ITINERARIO varchar(50) NOT NULL,
    UNIQUE KEY EJERCICIO (EJERCICIO,OLIMPIADA),
    KEY NOMBRE (NOMBRE),
    KEY OLIMPIADA (OLIMPIADA),
    KEY ITINERARIO (ITINERARIO),
    CONSTRAINT T_MONITORES_ibfk_1 FOREIGN KEY (NOMBRE) REFERENCES T_USUARIOS (NOMBRE) ON UPDATE CASCADE,
    CONSTRAINT T_MONITORES_ibfk_2 FOREIGN KEY (EJERCICIO) REFERENCES T_EJERCICIOS (CODIGO) ON UPDATE CASCADE,
    CONSTRAINT T_MONITORES_ibfk_3 FOREIGN KEY (OLIMPIADA) REFERENCES T_OLIMPIADAS (CODIGO) ON UPDATE CASCADE,
    CONSTRAINT T_MONITORES_ibfk_4 FOREIGN KEY (ITINERARIO) REFERENCES T_ITINERARIOS (CODIGO) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS T_ORGANIZADORES (
    ORGANIZADOR varchar(20) DEFAULT NULL,
    ITINERARIO varchar(50) DEFAULT NULL,
    UNIQUE KEY ORGANIZADOR (ORGANIZADOR,ITINERARIO),
    KEY ITINERARIO (ITINERARIO),
    CONSTRAINT T_ORGANIZADORES_ibfk_1 FOREIGN KEY (ORGANIZADOR) REFERENCES T_USUARIOS (NOMBRE) ON UPDATE CASCADE,
    CONSTRAINT T_ORGANIZADORES_ibfk_2 FOREIGN KEY (ITINERARIO) REFERENCES T_ITINERARIOS (CODIGO) ON UPDATE CASCADE
);

INSERT INTO T_USUARIOS (NOMBRE, PASSWORD, TIPO)
SELECT * FROM (SELECT 'ADMIN1' AS NOMBRE, 'ADMIN1' AS PASSWORD, 'ADMINISTRADOR' AS TIPO) AS tmp
WHERE NOT EXISTS (
    SELECT NOMBRE FROM T_USUARIOS WHERE NOMBRE = 'ADMIN1'
) LIMIT 1;
