CREATE TABLE T_OLYMPIADS (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100),
    YEAR INT NOT NULL,
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP NOT NULL,
    TIMEZONE VARCHAR(30)
);

CREATE TABLE T_ITINERARIES (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    OLYMPIAD VARCHAR(30) NOT NULL,
    UNIQUE (NAME, OLYMPIAD),
    FOREIGN KEY (OLYMPIAD)
        REFERENCES T_OLYMPIADS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_RUBRICS (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    POINTS VARCHAR(50) NOT NULL,
    LABELS VARCHAR(300)
);

CREATE TABLE T_EXERCISES (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    CATEGORY VARCHAR(40) NOT NULL CHECK (CATEGORY IN (
        'ABSTRACTION','ALGORITHMS','LOOPS','CONDITIONALS','COMPOSITION',
        'FUNCTIONS','AI','PATTERNS RECOGNITION','SEQUENCES',
        'LOOPS AND SEQUENCES','VARIABLES','VARIABLES AND FUNCTIONS','OTHER'
    )),
    RESOURCES VARCHAR(50) NOT NULL
);

CREATE TABLE T_UNPLUGGED_EXERCISES (
    ID VARCHAR(30) PRIMARY KEY,
    RUBRIC VARCHAR(30) NOT NULL,
    FOREIGN KEY (ID)
        REFERENCES T_EXERCISES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (RUBRIC)
        REFERENCES T_RUBRICS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_PLUGGED_IN_EXERCISES (
    ID VARCHAR(30) PRIMARY KEY,
    INPUTS INT NOT NULL,
    TIME_LIMIT INT,
    TESTCASE_VALUE DECIMAL(2) NOT NULL,
    WORDING_FILE VARCHAR(34),
    INPUT_FILES VARCHAR(34),
    OUTPUT_FILES VARCHAR(34),
    FOREIGN KEY (ID)
        REFERENCES T_EXERCISES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_EXERCISES_OLYMPIAD_ITINERARY (
    EXERCISE VARCHAR(30) NOT NULL,
    OLYMPIAD VARCHAR(30) NOT NULL,
    ITINERARY VARCHAR(30) NOT NULL,
    PRIMARY KEY (EXERCISE, OLYMPIAD, ITINERARY),
    FOREIGN KEY (EXERCISE)
        REFERENCES T_EXERCISES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (OLYMPIAD)
        REFERENCES T_OLYMPIADS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_SCHOOLS (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    TOWN VARCHAR(200),
    UNIQUE (NAME, TOWN)
);

CREATE TABLE T_TEAMS (
    ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SCHOOL VARCHAR(30) NOT NULL,
    ITINERARY VARCHAR(30) NOT NULL,
    UNIQUE (NAME, ITINERARY),
    FOREIGN KEY (SCHOOL)
        REFERENCES T_SCHOOLS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_USERS (
    ID VARCHAR(30) PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    TYPE VARCHAR(20) CHECK (TYPE IN ('ADMIN','MONITOR','ORGANIZER', 'PARTICIPANT'))
);

CREATE TABLE T_MONITORS (
    ID VARCHAR(30) NOT NULL,
    EXERCISE VARCHAR(30) NOT NULL,
    ITINERARY VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID, EXERCISE, ITINERARY),
    FOREIGN KEY (ID)
        REFERENCES T_USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (EXERCISE)
        REFERENCES T_EXERCISES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_ORGANIZERS (
    ID VARCHAR(30),
    ITINERARY VARCHAR(30),
    PRIMARY KEY (ID, ITINERARY),
    FOREIGN KEY (ID)
        REFERENCES T_USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_PARTICIPANTS (
    ID VARCHAR(30),
    SCHOOL VARCHAR(30) NOT NULL,
    ITINERARY VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID, ITINERARY),
    FOREIGN KEY (ID)
        REFERENCES T_USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (SCHOOL)
        REFERENCES T_SCHOOLS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_U_RANKING (
    TEAM VARCHAR(30),
    EXERCISE VARCHAR(30),
    ITINERARY VARCHAR(30),
    SCORE INT,
    PRIMARY KEY (TEAM, EXERCISE, ITINERARY),
    FOREIGN KEY (TEAM)
        REFERENCES T_TEAMS(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (EXERCISE)
        REFERENCES T_EXERCISES(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE T_P_RANKING (
    PARTICIPANT VARCHAR(30),
    EXERCISE VARCHAR(30),
    ITINERARY VARCHAR(30),
    SCORE INT,
    PRIMARY KEY (PARTICIPANT, EXERCISE, ITINERARY),
    FOREIGN KEY (PARTICIPANT, ITINERARY)
        REFERENCES T_PARTICIPANTS (ID, ITINERARY)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (EXERCISE)
        REFERENCES T_EXERCISES(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ITINERARY)
        REFERENCES T_ITINERARIES(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Insertar admin inicial solo si NO existe
INSERT INTO T_USERS (ID, USERNAME, PASSWORD, TYPE)
SELECT 'ADMIN1', 'ADMIN1', 'ADMIN', 'ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM T_USERS WHERE USERNAME = 'ADMIN1'
);
